# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Noise2Model',
                'doc_host': 'https://bmandracchia.github.io',
                'git_url': 'https://github.com/bmandracchia/Noise2Model',
                'lib_path': 'Noise2Model'},
  'syms': {'Noise2Model.core': {'Noise2Model.core.get_gt': ('test.html#get_gt', 'Noise2Model/core.py')}}}
