# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['get_gt', 'get_noisy_pair']

# %% ../nbs/00_core.ipynb 6
from fastai.vision.all import *
from fastai.data.all import *
import torch.nn.functional as F

# %% ../nbs/00_core.ipynb 9
def get_gt(path, gt_file_name="avg50.png"): 
    def _fn(fn): return Path(path/"gt")/f"{parent_label(fn)}"/gt_file_name
    return _fn

# %% ../nbs/00_core.ipynb 12
from random import randint

def get_noisy_pair(fn):
    tmp = get_image_files(fn.parent, recurse=False)
    fn2 = tmp[randint(0,len(tmp)-1)]
    while fn2 == fn: fn2 = tmp[randint(0,len(tmp)-1)]
    return fn2
