# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_core.ipynb.

# %% auto 0
__all__ = ['get_gt']

# %% ../nbs/01_core.ipynb 3
from fastai.vision.all import *
from fastai.data.all import *

def get_gt(fn, path, gt_file_name="avg50.png"): return Path(path/"gt")/f"{parent_label(fn)}"/gt_file_name
