# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_layers.ipynb.

# %% auto 0
__all__ = ['AffineSdn', 'Unconditional', 'Gain']

# %% ../nbs/02_layers.ipynb 4
from fastai.vision.all import nn, torch, np, Path, get_image_files, Image 
import normflows as nf
from .utils import attributesFromDict
# from Noise2Model.models import DnCNN, UNet
from .utils import gaussian_diag #, batch_PSNR, weights_init_orthogonal #, weights_init_kaiming


# %% ../nbs/02_layers.ipynb 12
from normflows.flows import GlowBlock, AffineConstFlow, Flow


# %% ../nbs/02_layers.ipynb 13
class AffineSdn(Flow):
    """
    Sdn flow layer
    """

    def __init__(self, shape):
        """Constructor

        
        """
        super().__init__()
        self.shape = shape
        self.affine = AffineConstFlow(self.shape)

    def forward(self, z, **kwargs):
        if 'clean' in kwargs:
            y = kwargs['clean']
        else:
            y = z
        y_, log_det = self.affine(y)
        return z * torch.sqrt(y_), log_det

    def inverse(self, z, **kwargs):
        y_, log_det = self.affine(y)
        return z / torch.sqrt(y_), log_det

# %% ../nbs/02_layers.ipynb 14
class Unconditional(Flow):
    """
    Unconditional flow layer
    """

    def __init__(self, channels, hidden_channels, split_mode):
        """Constructor

        
        """
        super().__init__()
        attributesFromDict(locals())
        self.glow = GlowBlock(channels=self.channels, hidden_channels = self.hidden_channels, split_mode=self.split_mode)

    def forward(self, z, **kwargs):
        z, log_det_tot = self.glow(z)
        return z, log_det_tot

    def inverse(self, z, **kwargs):
        z, log_det_tot = self.glow.inverse(z)
        

# %% ../nbs/02_layers.ipynb 15
class Gain(Flow):
    """
    Gain & Offset flow layer
    """

    def __init__(self, shape):
        """Constructor

        
        """
        super().__init__()
        self.shape = shape
        self.gain = AffineConstFlow(self.shape)

    def forward(self, z, **kwargs):
        return self.gain(z)

    def inverse(self, z, **kwargs):
        return self.gain.inverse(z)
