# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/91_Test.ipynb.

# %% auto 0
__all__ = ['get_gt']

# %% ../nbs/91_Test.ipynb 5
def get_gt(fn): return path_train_gt/f"{parent_label(fn)}"/"avg50.png"
